services:
  traefik:
    image: traefik:v3.6.5
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./.docker/traefik/le-http-acme.json:/le-http-acme.json # SSL sertifikalarının saklanacağı dosya
      - ./.docker/traefik/le-cloudflare-acme.json:/le-cloudflare-acme.json # SSL sertifikalarının saklanacağı dosya
      - /etc/localtime:/etc/localtime:ro
      - /var/log/traefik:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker'ı dinlemesi için şart
    command:
      # Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Logging
      - "--log.level=INFO"

      # Access Log
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/var/log/traefik/access.log"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-network"

      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      ## HTTP -> HTTPS Automatic Redirection
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      ## Bu ayar, X-Forwarded-For başlığının silinmesini engeller. Cloudflare ve Docker NAT arkasında olduğun için bu şart.
      - "--entryPoints.web.forwardedHeaders.trustedIPs=${TRUSTED_IPS}"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=${TRUSTED_IPS}"

      ####################################################################################################
      # HTTP Challenge (Alternative)
      - "--certificatesresolvers.le-http.acme.email=${LE_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.le-http.acme.storage=/le-http-acme.json"
      - "--certificatesresolvers.le-http.acme.httpchallenge=true"
      - "--certificatesresolvers.le-http.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.le-http.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # Staging Let's Encrypt (Only Test) Server
      ####################################################################################################
      # DNS Challenge (Cloudflare)
      - "--certificatesresolvers.le-cloudflare.acme.email=${LE_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.le-cloudflare.acme.storage=/le-cloudflare-acme.json"
      - "--certificatesresolvers.le-cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.le-cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le-cloudflare.acme.dnschallenge.delaybeforecheck=0"
      #- "--certificatesresolvers.le-cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # Staging Let's Encrypt (Only Test) Server
      ####################################################################################################
    labels:
      - "traefik.enable=true"

      # TLS Domains for Wildcard Certificates
      - "traefik.http.routers.traefik.tls.domains[0].main=${INTERNAL_SERVICE_DOMAIN}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${INTERNAL_SERVICE_DOMAIN}"

      # Traefik Dashboard Router
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-traefik.localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=le-http"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=internal@docker" # Security Middleware

      # 1️⃣ IP Allowlist
      - "traefik.http.middlewares.internal.ipallowlist.sourcerange=${INTERNAL_IP_ALLOWLIST}"
      - "traefik.http.middlewares.internal.ipallowlist.ipstrategy.depth=1"

      # 2️⃣ CrowdSec ForwardAuth
      - "traefik.http.middlewares.crowdsec.forwardauth.address=http://crowdsec-traefik-bouncer:8080/api/v1/forwardAuth"
      - "traefik.http.middlewares.crowdsec.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.crowdsec.forwardauth.authResponseHeaders=X-Crowdsec-Reason"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-network
    restart: unless-stopped

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      COLLECTIONS: "crowdsecurity/http-cve crowdsecurity/traefik"
      GID: "1000"
      DISABLE_HUB_UPGRADE: ${CROWDSEC_HUB_UPGRADE_DISABLE}
    volumes:
      - crowdsec-data:/var/lib/crowdsec/data
      - crowdsec-config:/etc/crowdsec
      - ./.docker/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./.docker/crowdsec/whitelists:/etc/crowdsec/parsers/s02-enrich/whitelists:ro
      - /var/log/traefik:/var/log/traefik:ro
    networks:
      - traefik-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "cscli", "lapi", "status" ]
      interval: 10s
      timeout: 60s
      retries: 5

  crowdsec-traefik-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    container_name: crowdsec-traefik-bouncer
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_TRAEFIK_BOUNCER_API_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080
      PORT: 8080
      GIN_MODE: "release"
      FAIL_OPEN: "true"
      TRUSTED_PROXIES: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,${TRUSTED_IPS}"
      CACHE_SIZE: ${CROWDSEC_TRAEFIK_CACHE_SIZE}
      CACHE_TTL: ${CROWDSEC_TRAEFIK_CACHE_TTL}
    networks:
      - traefik-network
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy

  crowdsec-cloudflare-bouncer:
    image: crowdsecurity/cloudflare-bouncer:latest
    container_name: crowdsec-cloudflare-bouncer
    environment:
      - CROWDSEC_LAPI_URL=${CROWDSEC_LAPI_URL}
      - CROWDSEC_LAPI_KEY=${CROWDSEC_CLOUDFLARE_BOUNCER_API_KEY}
      - CROWDSEC_UPDATE_FREQUENCY=360m
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - CLOUDFLARE_UPDATE_FREQUENCY=5m
    volumes:
      - .docker/crowdsec/bouncers/cloudflare-bouncer.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml:ro
    networks:
      - traefik-network
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy

  crowdsec-manager:
    image: hhftechnology/crowdsec-manager:latest
    container_name: crowdsec-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      CROWDSEC_LAPI_KEY: ${CROWDSEC_MANAGER_API_KEY}
      TZ: Europe/Istanbul
    labels:
      - "traefik.enable=true"

      # Routers
      - "traefik.http.routers.crowdsec-manager.rule=Host(`${CROWDSEC_DASHBOARD_HOST:-crowdsec.localhost}`)"
      - "traefik.http.routers.crowdsec-manager.entrypoints=websecure"
      - "traefik.http.routers.crowdsec-manager.tls.certresolver=le-http"
      - "traefik.http.routers.crowdsec-manager.service=crowdsec-manager"
      - "traefik.http.routers.crowdsec-manager.middlewares=internal@docker" # Security Middleware

      # Services
      - "traefik.http.services.crowdsec-manager.loadbalancer.server.port=8080"
    networks:
      - traefik-network
    restart: unless-stopped

volumes:
  crowdsec-data:
    driver: local
  crowdsec-config:
    driver: local

networks:
  traefik-network:
    external: true
